### ISSUE TITLE
build: the published package cannot be imported by Node, and its types fail under node16/nodenext

### ISSUE THREAD

**Issue by MaksymStoianov** [MaksymStoianov/apps-script-utils#553]
The package declares `"type": "module"`, but it is compiled with `"moduleResolution": "bundler"`, so `tsc` emits directory specifiers with no extension:

```js
// dist/index.js
export * from "./exception";
```

Node cannot resolve those. Installed from the registry, 2.1.1 behaves like this:

```
$ npm i apps-script-utils@2.1.1
$ node --input-type=module -e 'import {isString} from "apps-script-utils"'
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '.../dist/exception' is not supported
```

The same shape reaches the declarations, so a consumer whose project resolves modules the way Node does gets nothing at all:

```
$ tsc --module nodenext --moduleResolution nodenext
node_modules/apps-script-utils/dist/index.d.ts(1,15): error TS2834: Relative import paths need
explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'.
```

A bundler — vite, webpack, esbuild, rollup — resolves all of it, and so does a TypeScript project on `"moduleResolution": "bundler"`, which is why the clasp path has never noticed. Verified working on 2.1.1: `bundler` resolution with `skipLibCheck` compiles clean.

This is not a regression; 1.9.0 was published with the same shape.

The fix is an `exports` map and an emit that names files explicitly, which changes what the package promises its consumers, so it belongs in a minor release rather than a patch.
